Form/Type/SwitchType.php
<?php
namespace Innomedio\BackendThemeBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SwitchType extends AbstractType
{
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'required' => false
        ));
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return CheckboxType::class;
    }
}

Resources/views/profiler/backend_sidebar.html.twig
{% extends '@WebProfiler/Profiler/layout.html.twig' %}

{% block toolbar %}
    {% if collector.isBackend %}
        {% set icon %}
            <span style="opacity: 0.7; margin-right: 5px;">{% include '@InnomedioBackendTheme/profiler/backend_sidebar_icon.html.twig' %}</span>
            <span class="sf-toolbar-value">Sidebar</span>
        {% endset %}

        {% set text %}
            <div class="sf-toolbar-info-piece">
                <b>Items</b>
                <span>{{ collector.sidebarAmount }}</span>
            </div>
        {% endset %}

        {{ include('@WebProfiler/Profiler/toolbar_item.html.twig') }}
    {% endif %}
{% endblock %}

{% block menu %}
    <span class="label">
        <span class="icon">{% include "@InnomedioBackendTheme/profiler/backend_sidebar_icon.html.twig" %}</span>
        <strong>Backend sidebar</strong>
    </span>
{% endblock %}

{% block panel %}
    {# Optional, for showing the most details. #}
    <h2>Backend sidebar</h2>
    <table>
        <tr>
            <th>Name</th>
            <th>Key</th>
            <th>Parent</th>
            <th>Order</th>
        </tr>

        {% for mainItem in collector.sidebarItems %}
            <tr>
                <td>{{ mainItem.item.name|trans }}</td>
                <td>{{ mainItem.item.tag }}</td>
                <td>{{ mainItem.item.parent }}</td>
                <td>{{ mainItem.item.order }}</td>
            </tr>

            {% if mainItem.items|default(false) %}
                {% for subItem in mainItem.items %}
                    <tr>
                        <td>{{ subItem.name|trans }}</td>
                        <td>{{ subItem.tag }}</td>
                        <td>{{ subItem.parent.tag }}</td>
                        <td>{{ subItem.order }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

Resources/views/profiler/backend_sidebar_icon.html.twig
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 60.123 60.123" style="enable-background:new 0 0 60.123 60.123;" xml:space="preserve" width="512px" height="512px">
<g>
    <path d="M57.124,51.893H16.92c-1.657,0-3-1.343-3-3s1.343-3,3-3h40.203c1.657,0,3,1.343,3,3S58.781,51.893,57.124,51.893z" fill="#FFFFFF"/>
    <path d="M57.124,33.062H16.92c-1.657,0-3-1.343-3-3s1.343-3,3-3h40.203c1.657,0,3,1.343,3,3   C60.124,31.719,58.781,33.062,57.124,33.062z" fill="#FFFFFF"/>
    <path d="M57.124,14.231H16.92c-1.657,0-3-1.343-3-3s1.343-3,3-3h40.203c1.657,0,3,1.343,3,3S58.781,14.231,57.124,14.231z" fill="#FFFFFF"/>
    <circle cx="4.029" cy="11.463" r="4.029" fill="#FFFFFF"/>
    <circle cx="4.029" cy="30.062" r="4.029" fill="#FFFFFF"/>
    <circle cx="4.029" cy="48.661" r="4.029" fill="#FFFFFF"/>
</g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
    <g>
    </g>
</svg>